export const sampleProject: Project = {
  "id": "proj-001",
  "title": "Cloud Native E-commerce Platform Migration",
  "description": "Migrate existing monolithic e-commerce application to a scalable, microservices-based cloud-native architecture.",
  "status": "In Progress",
  "assignedUsers": [
    {
      "id": "user-dev-001",
      "name": "Alice Developer",
      "avatarUrl": "https://placehold.co/40x40/FF5733/FFFFFF?text=AD"
    },
    {
      "id": "user-dev-002",
      "name": "Bob Architect",
      "avatarUrl": "https://placehold.co/40x40/33FF57/FFFFFF?text=BA"
    },
    {
      "id": "user-dev-003",
      "name": "Charlie QA",
      "avatarUrl": "https://placehold.co/40x40/3357FF/FFFFFF?text=CQ"
    },
    {
      "id": "user-dev-004",
      "name": "Diana UI/UX",
      "avatarUrl": "https://placehold.co/40x40/FF33F5/FFFFFF?text=DU"
    }
  ],
  "createdAt": "2025-06-01",
  "updatedAt": "2025-07-29",
  "tasks": [
    {
      "id": "task-001",
      "title": "Setup Kubernetes Cluster for Dev Environment",
      "description": "Provision and configure a Kubernetes cluster on AWS EKS for development and testing purposes.",
      "label": "DevOps",
      "status": "In Progress",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 2,
      "taskImg": "https://placehold.co/150x100/A0A0A0/FFFFFF?text=K8s",
      "linksCount": 3,
      "commentsCount": 7,
      "dueDate": "2025-08-05T23:59:59.000Z"
    },
    {
      "id": "task-002",
      "title": "Implement User Authentication Service (Auth-Service)",
      "description": "Develop a Spring Boot microservice for user registration, login, and JWT generation.",
      "label": "Backend",
      "status": "To Do",
      "priority": "Critical",
      "priorityColor": "#DC3545",
      "assignedCount": 3,
      "linksCount": 2,
      "commentsCount": 12,
      "dueDate": "2025-08-10T23:59:59.000Z"
    },
    {
      "id": "task-003",
      "title": "Design Database Schema for Product Catalog",
      "description": "Create ER diagrams and define tables for product information, categories, and inventory.",
      "label": "Database",
      "status": "Approved",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 1,
      "linksCount": 1,
      "commentsCount": 5,
      "dueDate": "2025-07-20T23:59:59.000Z"
    },
    {
      "id": "task-004",
      "title": "Develop Product Catalog API Endpoints",
      "description": "",
      "label": "Backend",
      "status": "In Progress",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 2,
      "linksCount": 4,
      "commentsCount": 9,
      "dueDate": "2025-08-15T23:59:59.000Z"
    },
    {
      "id": "task-005",
      "title": "Integrate Next.js Frontend with Auth-Service",
      "description": "Connect the Next.js login/registration forms to the new authentication microservice.",
      "label": "Frontend",
      "status": "To Do",
      "priority": "Critical",
      "priorityColor": "#DC3545",
      "assignedCount": 2,
      "linksCount": 1,
      "commentsCount": 3,
      "dueDate": "2025-08-12T23:59:59.000Z"
    },
    {
      "id": "task-006",
      "title": "Refactor Legacy Payment Gateway Integration",
      "description": "Replace old payment gateway code with a new, modular service using Stripe API.",
      "label": "Refactor",
      "status": "Reject",
      "priority": "Medium",
      "priorityColor": "#007BFF",
      "assignedCount": 1,
      "linksCount": 0,
      "commentsCount": 2,
      "dueDate": "2025-07-25T23:59:59.000Z"
    },
    {
      "id": "task-007",
      "title": "Implement Shopping Cart Microservice",
      "description": "Develop a dedicated service for managing user shopping carts and their contents.",
      "label": "Backend",
      "status": "In Progress",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 2,
      "linksCount": 3,
      "commentsCount": 11,
      "dueDate": "2025-08-20T23:59:59.000Z"
    },
    {
      "id": "task-008",
      "title": "Design Product Detail Page UI/UX",
      "description": "Create wireframes and mockups for the new product detail page on the frontend.",
      "label": "UI/UX",
      "status": "To Do",
      "priority": "Medium",
      "priorityColor": "#007BFF",
      "assignedCount": 1,
      "linksCount": 0,
      "commentsCount": 4,
      "dueDate": "2025-08-08T23:59:59.000Z"
    },
    {
      "id": "task-009",
      "title": "Setup CI/CD Pipeline for Backend Services",
      "description": "Configure Jenkins/GitLab CI to automate build, test, and deployment of Spring Boot services.",
      "label": "DevOps",
      "status": "Approved",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 2,
      "linksCount": 5,
      "commentsCount": 15,
      "dueDate": "2025-07-10T23:59:59.000Z"
    },
    {
      "id": "task-010",
      "title": "Develop Order Processing Microservice",
      "description": "Build a service to handle order creation, status updates, and fulfillment.",
      "label": "Backend",
      "status": "In Progress",
      "priority": "Critical",
      "priorityColor": "#DC3545",
      "assignedCount": 3,
      "linksCount": 2,
      "commentsCount": 10,
    },
    {
      "id": "task-011",
      "title": "Implement Frontend Product Listing Page",
      "description": "Develop the React component for displaying products with pagination and filtering.",
      "label": "Frontend",
      "status": "To Do",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 2,
      "linksCount": 1,
      "commentsCount": 6,
    },
    {
      "id": "task-012",
      "title": "Bug: Checkout process occasionally hangs",
      "description": "Investigate and fix the intermittent hanging issue during the final checkout step.",
      "label": "Bug",
      "status": "In Progress",
      "priority": "Critical",
      "priorityColor": "#DC3545",
      "assignedCount": 1,
      "taskImg": "",
      "linksCount": 1,
      "commentsCount": 8,
    },
    {
      "id": "task-013",
      "title": "Setup Centralized Logging with ELK Stack",
      "description": "Configure Elasticsearch, Logstash, and Kibana for aggregated logging of all microservices.",
      "label": "DevOps",
      "status": "To Do",
      "priority": "Medium",
      "priorityColor": "#007BFF",
      "assignedCount": 2,
      "taskImg": "",
      "linksCount": 0,
      "commentsCount": 3,
    },
    {
      "id": "task-014",
      "title": "Develop User Profile Management Features",
      "description": "Implement API endpoints for viewing and updating user profile information.",
      "label": "Backend",
      "status": "Approved",
      "priority": "Medium",
      "priorityColor": "#007BFF",
      "assignedCount": 2,
      "taskImg": "",
      "linksCount": 2,
      "commentsCount": 7,
    },
    {
      "id": "task-015",
      "title": "Conduct Performance Testing on Auth-Service",
      "description": "Run load tests on the authentication service to identify bottlenecks and ensure scalability.",
      "label": "Testing",
      "status": "In Progress",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 1,
      "taskImg": "",
      "linksCount": 1,
      "commentsCount": 4,
    },
    {
      "id": "task-016",
      "title": "Frontend: Implement User Dashboard",
      "description": "Create the main user dashboard page displaying recent orders, profile links, etc.",
      "label": "Frontend",
      "status": "To Do",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 2,
      "taskImg": "",
      "linksCount": 0,
      "commentsCount": 5,
    },
    {
      "id": "task-017",
      "title": "Refactor: Migrate from JUnit 4 to JUnit 5",
      "description": "Update all existing backend tests to use JUnit 5 annotations and features.",
      "label": "Refactor",
      "status": "Approved",
      "priority": "Low",
      "priorityColor": "#6C757D",
      "assignedCount": 1,
      "taskImg": "",
      "linksCount": 1,
      "commentsCount": 2,
    },
    {
      "id": "task-018",
      "title": "Bug: Image upload fails on product creation",
      "description": "Investigate why product images are not being uploaded correctly to S3 bucket.",
      "label": "Bug",
      "status": "In Progress",
      "priority": "Critical",
      "priorityColor": "#DC3545",
      "assignedCount": 1,
      "taskImg": "",
      "linksCount": 1,
      "commentsCount": 10,
    },
    {
      "id": "task-019",
      "title": "Set up API Gateway with Spring Cloud Gateway",
      "description": "Configure routing, load balancing, and security for microservices using Spring Cloud Gateway.",
      "label": "DevOps",
      "status": "To Do",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 2,
      "taskImg": "",
      "linksCount": 2,
      "commentsCount": 6,
    },
    {
      "id": "task-020",
      "title": "Implement Admin Panel for Product Management",
      "description": "Develop a basic admin UI for creating, updating, and deleting products.",
      "label": "Frontend",
      "status": "In Progress",
      "priority": "Medium",
      "priorityColor": "#007BFF",
      "assignedCount": 1,
      "taskImg": "",
      "linksCount": 0,
      "commentsCount": 3,
    },
    {
      "id": "task-021",
      "title": "Database Migration: Add 'last_login' field to User",
      "description": "Create a new migration script to add a 'last_login' timestamp column to the users table.",
      "label": "Database",
      "status": "Approved",
      "priority": "Low",
      "priorityColor": "#6C757D",
      "assignedCount": 1,
      "taskImg": "",
      "linksCount": 1,
      "commentsCount": 1,
    },
    {
      "id": "task-022",
      "title": "Research: Distributed Tracing with OpenTelemetry",
      "description": "Investigate how to integrate OpenTelemetry for end-to-end tracing across microservices.",
      "label": "Research",
      "status": "To Do",
      "priority": "Medium",
      "priorityColor": "#007BFF",
      "assignedCount": 1,
      "taskImg": "https://placehold.co/150x100/A0A0A0/FFFFFF?text=Trace",
      "linksCount": 0,
      "commentsCount": 1,
    },
    {
      "id": "task-023",
      "title": "Bug: User profile update sometimes fails silently",
      "description": "Identify the root cause of silent failures when users attempt to update their profile information.",
      "label": "Bug",
      "status": "Reject",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 1,
      "taskImg": "https://placehold.co/150x100/A0A0A0/FFFFFF?text=Bug",
      "linksCount": 1,
      "commentsCount": 4,
    },
    {
      "id": "task-024",
      "title": "Implement Notification Service (Email/SMS)",
      "description": "Develop a microservice for sending transactional emails and SMS notifications.",
      "label": "Backend",
      "status": "In Progress",
      "priority": "High",
      "priorityColor": "#FFC107",
      "assignedCount": 2,
      "taskImg": "https://placehold.co/150x100/A0A0A0/FFFFFF?text=Notif",
      "linksCount": 2,
      "commentsCount": 8,
    },
    {
      "id": "task-025",
      "title": "Frontend: Implement Search Bar and Filtering",
      "description": "Add a functional search bar and basic filtering options to the product listing page.",
      "label": "Frontend",
      "status": "To Do",
      "priority": "Medium",
      "priorityColor": "#007BFF",
      "assignedCount": 1,
      "taskImg": "https://placehold.co/150x100/A0A0A0/FFFFFF?text=Search",
      "linksCount": 0,
      "commentsCount": 2,
    }
  ]
}